/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedWorkflowRouteImport } from './routes/_authed/workflow'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedPapersPaperIdIndexRouteImport } from './routes/_authed/papers/$paperId/index'
import { Route as AuthedPapersPaperIdEditRouteImport } from './routes/_authed/papers/$paperId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkflowRoute = AuthedWorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPapersPaperIdIndexRoute =
  AuthedPapersPaperIdIndexRouteImport.update({
    id: '/papers/$paperId/',
    path: '/papers/$paperId/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPapersPaperIdEditRoute = AuthedPapersPaperIdEditRouteImport.update({
  id: '/papers/$paperId/edit',
  path: '/papers/$paperId/edit',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/workflow': typeof AuthedWorkflowRoute
  '/papers/$paperId/edit': typeof AuthedPapersPaperIdEditRoute
  '/papers/$paperId/': typeof AuthedPapersPaperIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/workflow': typeof AuthedWorkflowRoute
  '/papers/$paperId/edit': typeof AuthedPapersPaperIdEditRoute
  '/papers/$paperId': typeof AuthedPapersPaperIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/workflow': typeof AuthedWorkflowRoute
  '/_authed/papers/$paperId/edit': typeof AuthedPapersPaperIdEditRoute
  '/_authed/papers/$paperId/': typeof AuthedPapersPaperIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/workflow'
    | '/papers/$paperId/edit'
    | '/papers/$paperId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/workflow'
    | '/papers/$paperId/edit'
    | '/papers/$paperId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/dashboard'
    | '/_authed/workflow'
    | '/_authed/papers/$paperId/edit'
    | '/_authed/papers/$paperId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/workflow': {
      id: '/_authed/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof AuthedWorkflowRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/papers/$paperId/': {
      id: '/_authed/papers/$paperId/'
      path: '/papers/$paperId'
      fullPath: '/papers/$paperId/'
      preLoaderRoute: typeof AuthedPapersPaperIdIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/papers/$paperId/edit': {
      id: '/_authed/papers/$paperId/edit'
      path: '/papers/$paperId/edit'
      fullPath: '/papers/$paperId/edit'
      preLoaderRoute: typeof AuthedPapersPaperIdEditRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedWorkflowRoute: typeof AuthedWorkflowRoute
  AuthedPapersPaperIdEditRoute: typeof AuthedPapersPaperIdEditRoute
  AuthedPapersPaperIdIndexRoute: typeof AuthedPapersPaperIdIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedWorkflowRoute: AuthedWorkflowRoute,
  AuthedPapersPaperIdEditRoute: AuthedPapersPaperIdEditRoute,
  AuthedPapersPaperIdIndexRoute: AuthedPapersPaperIdIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
