"use client";

import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { Check, ExternalLink, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { YouTubeIcon } from "@/components/icons/preview-modal-icons";
import { getSocialStatus, getYouTubeAuthUrl, shareToYouTube } from "@/lib/api";
import type { Artifact } from "@/lib/artifact-store";
import { GA_EVENTS, trackGAEvent } from "@/lib/gtag";
import { ShareHeader } from "./share-header";
import type { ShareState } from "./shared";
import Link from "next/link";

interface YouTubeShareProps {
  artifact: Artifact;
  initialTitle: string;
  onBack: () => void;
  onClose: () => void;
  onReturnToPreview: () => void;
}

export function YouTubeShare({
  artifact,
  initialTitle,
  onBack,
  onClose,
  onReturnToPreview,
}: YouTubeShareProps) {
  const [shareState, setShareState] = useState<ShareState>("loading");
  const [ytConnected, setYtConnected] = useState(false);
  const [title, setTitle] = useState(initialTitle);
  const [description, setDescription] = useState(
    "Generated by Saral — Paper to Video",
  );
  const [visibility, setVisibility] = useState("unlisted");
  const [resultUrl, setResultUrl] = useState("");
  const [errorMsg, setErrorMsg] = useState("");

  useEffect(() => {
    setTitle(initialTitle);
  }, [initialTitle]);

  useEffect(() => {
    setShareState("loading");
    getSocialStatus()
      .then((status) => {
        setYtConnected(status.youtube);
        setShareState(status.youtube ? "form" : "idle");
      })
      .catch(() => {
        setYtConnected(false);
        setShareState("idle");
      });
  }, []);

  const handleConnect = async () => {
    try {
      const { auth_url } = await getYouTubeAuthUrl();
      const width = 500;
      const height = 600;
      const left = window.screenX + (window.outerWidth - width) / 2;
      const top = window.screenY + (window.outerHeight - height) / 2;
      const popup = window.open(
        auth_url,
        "youtube_oauth",
        `width=${width},height=${height},left=${left},top=${top},toolbar=no,menubar=no`,
      );

      setShareState("loading");

      const pollInterval = setInterval(async () => {
        try {
          if (popup && popup.closed) {
            clearInterval(pollInterval);
            const status = await getSocialStatus();
            if (status.youtube) {
              setYtConnected(true);
              setShareState("form");
            } else {
              setShareState("idle");
            }
            return;
          }
          const status = await getSocialStatus();
          if (status.youtube) {
            clearInterval(pollInterval);
            setYtConnected(true);
            setShareState("form");
            if (popup && !popup.closed) popup.close();
          }
        } catch {
          // ignore polling errors
        }
      }, 2000);

      setTimeout(
        () => {
          clearInterval(pollInterval);
          if (shareState === "loading") {
            setShareState("idle");
          }
        },
        5 * 60 * 1000,
      );
    } catch {
      setErrorMsg("Failed to get auth URL");
      setShareState("error");
    }
  };

  const handleUpload = async () => {
    if (!artifact.runId) return;
    setShareState("uploading");
    setErrorMsg("");
    try {
      const result = await shareToYouTube(
        artifact.runId,
        title,
        description,
        visibility,
      );
      setResultUrl(result.url);
      setShareState("success");
      trackGAEvent(GA_EVENTS.SHARE_YOUTUBE, { artifact_type: artifact.type });
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Upload failed");
      setShareState("error");
    }
  };

  return (
    <motion.div
      key="share-youtube"
      initial={{ opacity: 0, x: 20 }}
      animate={{ opacity: 1, x: 0 }}
      exit={{ opacity: 0, x: 20 }}
      transition={{ duration: 0.2 }}
    >
      <ShareHeader
        title="Upload to YouTube"
        icon={<YouTubeIcon className="text-red-600 shrink-0" />}
        onBack={onBack}
        onClose={onClose}
      />
      <div className="px-7 py-6 max-sm:px-5 max-sm:py-5">
        {shareState === "loading" && (
          <div className="flex items-center justify-center py-16">
            <Loader2
              size={24}
              className="animate-spin text-ink-muted dark:text-white/70"
            />
          </div>
        )}

        {shareState === "idle" && !ytConnected && (
          <div className="flex flex-col items-center gap-4 py-10">
            <div className="w-14 h-14 rounded-full bg-red-50 flex items-center justify-center">
              <YouTubeIcon className="text-red-600" />
            </div>
            <div className="text-center">
              <p className="font-sans text-[15px] font-medium text-ink dark:text-white">
                Connect YouTube
              </p>
              <p className="font-sans text-[13px] text-ink-muted dark:text-white/70 mt-1 max-w-70">
                Link your YouTube account to upload videos directly from Saral.
              </p>
            </div>
            <Button
              onClick={handleConnect}
              className="flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white px-6"
            >
              <YouTubeIcon className="text-white" />
              Connect YouTube
            </Button>
          </div>
        )}

        {shareState === "form" && (
          <div className="space-y-5">
            {artifact.downloadUrl && (
              <div className="rounded-lg overflow-hidden bg-[#1a1a1a] aspect-video max-h-40 max-sm:max-h-30 w-full flex items-center justify-center">
                <video
                  src={artifact.downloadUrl}
                  className="w-full h-full object-contain"
                  muted
                />
              </div>
            )}
            <div>
              <label className="font-sans text-[13px] font-semibold text-ink dark:text-white mb-2.5 block">
                Title
              </label>
              <Input
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                placeholder="Video title"
                className="rounded-lg border-pill-border focus:ring-2 focus:ring-red-600 focus:border-transparent"
              />
            </div>
            <div>
              <label className="font-sans text-[13px] font-semibold text-ink dark:text-white mb-2.5 block">
                Description
              </label>
              <Textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Video description"
                rows={3}
                className="resize-none rounded-lg border-pill-border focus:ring-2 focus:ring-red-600 focus:border-transparent"
              />
            </div>
            <div>
              <label className="font-sans text-[13px] font-semibold text-ink dark:text-white mb-2.5 block">
                Visibility
              </label>
              <Select value={visibility} onValueChange={setVisibility}>
                <SelectTrigger className="w-full bg-white border-pill-border rounded-lg focus:ring-2 focus:ring-ink focus:border-transparent">
                  <SelectValue placeholder="Select visibility" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="unlisted">Unlisted</SelectItem>
                  <SelectItem value="public">Public</SelectItem>
                  <SelectItem value="private">Private</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <Button
              onClick={handleUpload}
              className="w-full flex items-center gap-2 bg-red-600 hover:bg-red-700 text-white rounded-lg py-2.5 text-[15px] font-semibold"
            >
              <YouTubeIcon className="text-white" />
              Upload to YouTube
            </Button>
          </div>
        )}

        {shareState === "uploading" && (
          <div className="flex flex-col items-center gap-4 py-12">
            <Loader2 size={28} className="animate-spin text-red-600" />
            <div className="text-center">
              <p className="font-sans text-[15px] font-medium text-ink dark:text-white">
                Uploading to YouTube...
              </p>
              <p className="font-sans text-[13px] text-ink-muted dark:text-white/70 mt-1">
                This may take a minute
              </p>
            </div>
          </div>
        )}

        {shareState === "success" && (
          <div className="flex flex-col items-center gap-4 py-10">
            <div className="w-14 h-14 rounded-full bg-green-100 flex items-center justify-center">
              <Check size={24} className="text-green-600" />
            </div>
            <div className="text-center">
              <p className="font-sans text-[15px] font-medium text-ink dark:text-white">
                Uploaded successfully!
              </p>
              <p className="font-sans text-[13px] text-ink-muted dark:text-white/70 mt-1">
                Your video is now on YouTube
              </p>
            </div>
            <Link
              href={resultUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-[14px] text-blue-600 hover:underline font-medium"
            >
              <ExternalLink size={14} />
              Open on YouTube
            </Link>
            <Button
              onClick={onReturnToPreview}
              variant="outline"
              className="mt-1"
            >
              Back to preview
            </Button>
          </div>
        )}

        {shareState === "error" && (
          <div className="space-y-4 py-4">
            <div className="rounded-lg bg-red-50 border border-red-200 p-3">
              <p className="font-sans text-[13px] text-red-700">{errorMsg}</p>
            </div>
            <div className="flex gap-2">
              <Button
                onClick={() => setShareState("form")}
                variant="outline"
                className="flex-1"
              >
                Try again
              </Button>
              <Button onClick={onBack} variant="ghost" className="flex-1">
                Back
              </Button>
            </div>
          </div>
        )}
      </div>
    </motion.div>
  );
}
