package pipeline

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/saral/script-gen/internal/gemini"
	"github.com/saral/script-gen/internal/webhook"
)

// ── LinkedIn ──────────────────────────────────────────────────────────────────

type linkedInDraft struct {
	Title   string `json:"title"`
	Caption string `json:"caption"`
}

// RunLinkedIn generates a LinkedIn post draft and uploads it to GCS.
func RunLinkedIn(ctx context.Context, gc gemini.Provider, deps Deps,
	runID, stepID, extractedPath, userID, paperID string,
) error {
	data, err := deps.Store.Download(ctx, extractedPath)
	if err != nil {
		return fmt.Errorf("download extracted: %w", err)
	}
	var extracted ExtractedDocument
	if err := json.Unmarshal(data, &extracted); err != nil {
		return fmt.Errorf("parse extracted.json: %w", err)
	}

	// Metadata and caption generation run concurrently
	type captionResult struct {
		caption string
		err     error
	}
	type metaResult struct {
		title string
		err   error
	}

	captionCh := make(chan captionResult, 1)
	metaCh := make(chan metaResult, 1)

	// We need the title before building the caption prompt, so we extract
	// metadata first and then fire the caption call in the same goroutine.
	// The metadata goroutine sends early so caption goroutine can start.
	go func() {
		meta, err := gemini.ExtractMetadata(ctx, gc, extracted.Text)
		if err != nil {
			metaCh <- metaResult{err: err}
			return
		}
		title := meta.Title
		if title == "" {
			title = "Research Paper"
		}
		metaCh <- metaResult{title: title}

		// Caption prompt needs the title, build it inline
		paperText := extracted.Text
		if len(paperText) > 3000 {
			paperText = paperText[:3000]
		}
		prompt := strings.NewReplacer(
			"{title}", title,
			"{paper_text}", paperText,
		).Replace(deps.Prompts.LinkedIn)

		log.Printf("[linkedin][%s] calling Gemini", runID)
		rawCaption, cerr := gemini.Generate(ctx, gc, gemini.ModelFlash, prompt)
		if cerr != nil {
			captionCh <- captionResult{err: cerr}
			return
		}

		cleaned := gemini.StripCodeFences(rawCaption)
		var liJSON struct {
			Caption string `json:"caption"`
		}
		captionText := cleaned
		if jsonErr := json.Unmarshal([]byte(cleaned), &liJSON); jsonErr == nil && liJSON.Caption != "" {
			captionText = liJSON.Caption
		}
		captionCh <- captionResult{caption: captionText}
	}()

	metaRes := <-metaCh
	if metaRes.err != nil {
		log.Printf("[linkedin][%s] metadata extraction failed, using fallback title: %v", runID, metaRes.err)
		metaRes.title = "Research Paper"
	}
	captionRes := <-captionCh
	if captionRes.err != nil {
		return fmt.Errorf("gemini linkedin caption: %w", captionRes.err)
	}

	caption := formatLinkedInCaption(captionRes.caption, metaRes.title)
	draft := linkedInDraft{Title: metaRes.title, Caption: caption}

	runUUID, _ := uuid.Parse(runID)
	objectKey := fmt.Sprintf("%s/%s/runs/%s/linkedin_draft/draft.json", userID, paperID, runUUID)
	draftBytes, _ := json.Marshal(draft)
	gcsPath, err := deps.Store.Upload(ctx, draftBytes, objectKey, "application/json")
	if err != nil {
		return fmt.Errorf("upload linkedin draft: %w", err)
	}

	webhook.Send(deps.GatewayURL, runID, stepID, "linkedin_draft", "completed", gcsPath, "", metaRes.title, "", "")
	log.Printf("[linkedin][%s] completed: output=%s", runID, gcsPath)
	return nil
}

// formatLinkedInCaption post-processes the Gemini caption:
//   - strips "**" markdown bold markers
//   - ensures #SARALAI hashtag is present
//   - prepends "Paper Titled: {title}" header
//   - appends video URL footer
func formatLinkedInCaption(raw, title string) string {
	cleaned := strings.ReplaceAll(raw, "**", "")
	cleaned = strings.TrimSpace(cleaned)
	lines := strings.Split(cleaned, "\n")

	hashtagIdx := -1
	for i, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "#") {
			hashtagIdx = i
			break
		}
	}

	if !strings.Contains(strings.ToUpper(cleaned), "#SARALAI") {
		if hashtagIdx >= 0 {
			lines[hashtagIdx] = strings.TrimRight(lines[hashtagIdx], " ") + " #SARALAI"
		} else {
			lines = append(lines, "#SARALAI")
		}
	}

	body := strings.Join(lines, "\n")
	videoLine := "🎥 Video has been generated by SARALAI: [Please paste your video URL]"
	return fmt.Sprintf("Paper Titled: %s\n\n%s\n\n%s", title, body, videoLine)
}

// ── Twitter / X ───────────────────────────────────────────────────────────────

type twitterThread struct {
	Title      string   `json:"title"`
	Tweets     []string `json:"tweets"`
	TweetCount int      `json:"tweet_count"`
}

// RunTwitter generates an X/Twitter thread and uploads it to GCS.
func RunTwitter(ctx context.Context, gc gemini.Provider, deps Deps,
	runID, stepID, extractedPath, userID, paperID string,
) error {
	data, err := deps.Store.Download(ctx, extractedPath)
	if err != nil {
		return fmt.Errorf("download extracted: %w", err)
	}
	var extracted ExtractedDocument
	if err := json.Unmarshal(data, &extracted); err != nil {
		return fmt.Errorf("parse extracted.json: %w", err)
	}

	meta, err := gemini.ExtractMetadata(ctx, gc, extracted.Text)
	if err != nil {
		log.Printf("[twitter][%s] metadata extraction failed, using fallback: %v", runID, err)
	}
	title := meta.Title
	if title == "" {
		title = "Untitled Research"
	}
	authors := meta.Authors
	if authors == "" {
		authors = "Unknown Authors"
	}
	year := meta.Date
	if year == "" {
		year = "N/A"
	}

	paperText := extracted.Text
	if len(paperText) > 4000 {
		paperText = paperText[:4000]
	}

	prompt := strings.NewReplacer(
		"{title}", title,
		"{authors}", authors,
		"{year}", year,
		"{paper_text}", paperText,
	).Replace(deps.Prompts.Twitter)

	log.Printf("[twitter][%s] calling Gemini", runID)
	rawThread, err := gemini.Generate(ctx, gc, gemini.ModelFlash, prompt)
	if err != nil {
		return fmt.Errorf("gemini twitter: %w", err)
	}

	var tweets []string
	cleaned := gemini.StripCodeFences(rawThread)
	var twJSON struct {
		Tweets []string `json:"tweets"`
	}
	if jsonErr := json.Unmarshal([]byte(cleaned), &twJSON); jsonErr == nil && len(twJSON.Tweets) > 0 {
		tweets = applyTweetNumbering(twJSON.Tweets)
	} else {
		tweets = parseAndFormatTweets(rawThread)
	}
	if len(tweets) == 0 {
		return fmt.Errorf("could not parse any tweets from Gemini response")
	}

	thread := twitterThread{Title: title, Tweets: tweets, TweetCount: len(tweets)}
	runUUID, _ := uuid.Parse(runID)
	objectKey := fmt.Sprintf("%s/%s/runs/%s/twitter_draft/thread.json", userID, paperID, runUUID)
	threadBytes, _ := json.Marshal(thread)
	gcsPath, err := deps.Store.Upload(ctx, threadBytes, objectKey, "application/json")
	if err != nil {
		return fmt.Errorf("upload twitter thread: %w", err)
	}

	webhook.Send(deps.GatewayURL, runID, stepID, "twitter_draft", "completed", gcsPath, "", title, "", "")
	log.Printf("[twitter][%s] completed: output=%s tweets=%d", runID, gcsPath, len(tweets))
	return nil
}

// ── Tweet formatting helpers ──────────────────────────────────────────────────

var blankLinesRE = regexp.MustCompile(`\n\s*\n+`)

func applyTweetNumbering(tweets []string) []string {
	total := len(tweets)
	numbered := make([]string, 0, total)
	for i, t := range tweets {
		t = blankLinesRE.ReplaceAllString(t, "\n")
		t = strings.TrimSpace(t)
		prefix := fmt.Sprintf("%s/%s ", toEmojiNumber(i+1), toEmojiNumber(total))
		tweet := prefix + t
		runes := []rune(tweet)
		if len(runes) > 280 {
			tweet = string(runes[:277]) + "..."
		}
		numbered = append(numbered, tweet)
	}
	return numbered
}

// parseAndFormatTweets is a legacy fallback for plain-text "N/ ..." format.
func parseAndFormatTweets(raw string) []string {
	tweetNumRE := regexp.MustCompile(`^\d+/`)
	lines := strings.Split(raw, "\n")
	var blocks []string
	var current strings.Builder
	for _, line := range lines {
		if tweetNumRE.MatchString(line) && current.Len() > 0 {
			blocks = append(blocks, strings.TrimSpace(current.String()))
			current.Reset()
		}
		current.WriteString(line)
		current.WriteRune('\n')
	}
	if current.Len() > 0 {
		if b := strings.TrimSpace(current.String()); b != "" {
			blocks = append(blocks, b)
		}
	}
	if len(blocks) == 0 {
		return nil
	}

	stripNum := regexp.MustCompile(`^\d+/\s?`)
	stripped := make([]string, 0, len(blocks))
	for _, m := range blocks {
		t := stripNum.ReplaceAllString(strings.TrimSpace(m), "")
		stripped = append(stripped, strings.TrimSpace(t))
	}
	return applyTweetNumbering(stripped)
}

// toEmojiNumber converts 1–99 to emoji digit string ("1️⃣", "🔟", etc.).
func toEmojiNumber(n int) string {
	if n == 10 {
		return "🔟"
	}
	digits := map[rune]string{
		'0': "0️⃣", '1': "1️⃣", '2': "2️⃣", '3': "3️⃣", '4': "4️⃣",
		'5': "5️⃣", '6': "6️⃣", '7': "7️⃣", '8': "8️⃣", '9': "9️⃣",
	}
	var b strings.Builder
	for _, d := range fmt.Sprintf("%d", n) {
		b.WriteString(digits[d])
	}
	return b.String()
}
